// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://gpvmlaxxzpmjzhobilyz.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwdm1sYXh4enBtanpob2JpbHl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI1NDMwOTgsImV4cCI6MjA0ODExOTA5OH0._MnhOQV2IvPVuPPM6kSCKGBSLBOVMWdxvZjTX5p7zEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);