// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://hednbacddsdanbubjsxb.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhlZG5iYWNkZHNkYW5idWJqc3hiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzI5NTEzNzUsImV4cCI6MjA0ODUyNzM3NX0.9iGKup-i6nk7v8nWMeZwZA_f6yndWGxe_ndWOW4MUj8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);